### ISSUE TITLE
Enemybuff question

### ISSUE THREAD

**Issue by Splaser** [rgd87/LibClassicDurations#14]
for i = 1 , MAX_TARGET_BUFFS do
            -- local name, icon, count, debuffType, duration, expirationTime, unitCaster, isStealable, shouldConsolidate, spellId  = UnitBuff(unit,i)
            local buffName, icon, count, debuffType, duration, expirationTime, caster, canStealOrPurge, _ , spellid, _, _, casterIsPlayer, nameplateShowAll= LibClassicDurations:UnitAura(unit, i, "HELPFUL");
            --print(buffName, icon, count, debuffType, duration, expirationTime, caster, canStealOrPurge, spellid)
            if buffName then
                ---#### debuffType is nil
                --if debuffType == "Magic" then
                    return buffName;                
                --end
            end
        end
I got debuffType nil for a priest mob with a stamina buff. But this debuffType was nil (should be Magic), others seemed work well.
How can I get correct debuffType for a mob?
Thank you for amazing work. btw

**Comment by d87** [comment]
You can't. the only thing game knows about enemy buffs is their name when they are applied. spell ID and icon are only guessed from that.

**Comment by Splaser** [comment]
OK. it seems I can only make an enrage buff list to distinguish magic buffs from them. There are usually 2 kinds of bufftypes from mobs lol.
