### ISSUE TITLE
Touch of Weakness

### ISSUE THREAD

**Issue by Finney74** [rgd87/LibClassicDurations#16]
In classAbilities.lua there is only a method to track the Touch of Weakness spell as a buff, but it also applies a 120 second debuff to the target when the effect is consumed.

I managed to get it working as a weakaura nameplate debuff by changing it from:

Spell({ 2652, 19261, 19262, 19264, 19265, 19266 }, { duration = 600, type = "BUFF", castFilter = true }) -- Touch of Weakness

To:

Spell({ 2652, 19261, 19262, 19264, 19265, 19266, 28598, 19320, 19322, 2943, 19251, 19252, 19253, 19254, 19318, 19429, 19321, 19323, 19324 }, { duration = 120 }) -- Touch of Weakness

**Comment by d87** [comment]
Alright, It's going to be 2m as a buff too now, but whatever. Neither of them actually matters
