### ISSUE TITLE
Iron Grenade

### ISSUE THREAD

**Issue by Finney74** [rgd87/LibClassicDurations#18]
Minor issue with the spell ID for Iron Grenade: 4068 does not track the duration of the stun/disorient effect. For some reason it is tracking it as a stack effect on the icon.

Managed to do a workaround and get a timer on the icon by changing:

Spell({ 4068, 19769, }, { duration = 3 }) -- Iron Grenade, Thorium

To:

Spell({ 4068, 19769, 4018 }, { duration = 3 }) -- Iron Grenade, Thorium

I can't make thorium grenades yet, so I don't know if the issue also affects them or not.

**Comment by d87** [comment]
thanks for reporting, fixed
