### ISSUE TITLE
Hunters Feign Death - resets timers on buffs.

### ISSUE THREAD

**Issue by Dyaxler** [rgd87/LibClassicDurations#21]
When tracking time remaining on buffs cast on Hunters, upon Feign Death the timers disappear.

**Comment by Dyaxler** [comment]
This issue is still occurring. Can you add a check to the routine that wipes timers upon death and add:

https://wow.gamepedia.com/API_UnitIsFeignDeath

If a Hunter feigns, then don't clear the duration and expiration's from the cache.

**Comment by Dyaxler** [comment]
![image](https://user-images.githubusercontent.com/17400948/67109553-9b4d7580-f185-11e9-8f65-debe94dc857b.png)

**Comment by Dyaxler** [comment]
I only briefly read through the code... so this is the only function that clears buff timers from the cache?

```
function f:NAME_PLATE_UNIT_REMOVED(event, unit)
    local unitGUID = UnitGUID(unit)
    if unitGUID then -- it returns correctly on death, but just in case
        nameplateUnitMap[unitGUID] = nil
    end
end
```

If so... then this should work right? :) I can add it to my local build and test.

```
function f:NAME_PLATE_UNIT_REMOVED(event, unit)
    local unitGUID = UnitGUID(unit)
    if unitGUID then -- it returns correctly on death, but just in case
	if (UnitIsFeignDeath(unit)) or (UnitAura("player", "Feign Death") ~= nil) then
		return
	else
		nameplateUnitMap[unitGUID] = nil
	end
    end
end
```

First check will check non-hunters. Second check checks hunters specifically according to:

> Details
> 
>     Only provides valid data for friendly units.
>     Does not work for the player character. Use UnitAura instead:
> 
> isFeign = UnitAura("player", "Feign Death") ~= nil

**Comment by d87** [comment]
nameplate functions have nothing to do with it
It's here
https://github.com/rgd87/LibClassicDurations/blob/7654b97c6594c438d54f4ca76369437522111cfb/core.lua#L568

UnitAura doesn't work like that anymore, it can't query by name in 8.0

You can try this simple check, but it's only MAYBE useful in pvp against hunters

    local isGUIDFeigning(guid) = function
        local targetGUID = UnitGUID("target")
        if targetGUID == guid and UnitIsFeignDeath("target") then return true end
        return false
    end

**Comment by d87** [comment]
Ok, get the latest github version of the lib and the next time you'll meet your hunter friend type with him as a target
/script LibStub("LibClassicDurations"):MonitorUnit("target")

**Comment by Dyaxler** [comment]
![image](https://user-images.githubusercontent.com/17400948/67112453-25004180-f18c-11e9-9e55-cf778692cbe1.png)

**Comment by d87** [comment]
And he had buffs before FD, right?

**Comment by Dyaxler** [comment]
So apparently I can only run the script once... then it stops for some odd reason. I figured out the quirk. The first screen shot is of a hunter feigning without buffs... this one had buffs.

![image](https://user-images.githubusercontent.com/17400948/67113242-d9e72e00-f18d-11e9-9c4e-8073b9975132.png)

When she popped back up the buff timers were zero even though the buff was still on her.

**Comment by d87** [comment]
Ok, here's a branch that tracks hunter guids. You can try it out
https://github.com/rgd87/LibClassicDurations/tree/FeignDeath

idk what's up with the debug stopping

**Comment by Dyaxler** [comment]
I just had to reload the UI then it started spitting back out strings

**Comment by Dyaxler** [comment]
I just read through the code and it looks like it'll ignore hunters completely?

The problem is that Hunters Feign death is treated as an actual death so the timers clear. You'd still want to clear the timers if a hunter actually dies... just not if they feign. Unfortunately, it looks as though CombatLogGetCurrentEventInfo() returns spellID: **-1** and spellName: **false** and not the actual spellName: **Feign Death**. There is no way to collate a UnitID from just a name so the following code will only work while in a party or raid which is fine since the only real way to check if a hunter is feigned is by using Blizzards UnitIsFeignDeath API and it requires a UnitID. At least addons that track buff timers for party and raid members won't get cleared. This code fixed my addon perfectly.

```
if eventType == "UNIT_DIED" then
				local _, englishClass, _, _, _, _, playerName = GetPlayerInfoByGUID(dstGUID)
				local isFeign = false
        if englishClass == "HUNTER" then
					if GetNumGroupMembers() < 6 then
						for i = 1, MAX_PARTY_MEMBERS do
							local unitID = party[i]
							if (UnitName(unitID) == playerName) and (UnitIsFeignDeath(unitID) or (UnitAura("player", "Feign Death") ~= nil)) then
								isFeign = true
							end
						end					
					else
						for i = 1, MAX_RAID_MEMBERS do
							local unitID = raid[i]
							if (UnitName(unitID) == playerName) and (UnitIsFeignDeath(unitID) or (UnitAura("player", "Feign Death") ~= nil)) then
								isFeign = true
							end
						end
					end
				elseif isFeign = false then
            guids[dstGUID] = nil
            buffCache[dstGUID] = nil
            buffCacheValid[dstGUID] = nil
            guidAccessTimes[dstGUID] = nil
            local isDstFriendly = bit_band(dstFlags, COMBATLOG_OBJECT_REACTION_FRIENDLY) > 0
            if enableEnemyBuffTracking and not isDstFriendly then
                FireToUnits("UNIT_BUFF", dstGUID)
            end
            nameplateUnitMap[dstGUID] = nil
        end
    end
```

**Comment by d87** [comment]
> GetPlayerInfoByGUID

Wth, never knew such a function exists

**Comment by Dyaxler** [comment]
https://wow.gamepedia.com/Global_functions/Classic

I almost have them all memorized. :D Just wait, next patch something else will change. *sigh*

Made a pull request to make code mergers easier. I thought maybe you want to bed...

**Comment by d87** [comment]
https://github.com/rgd87/LibClassicDurations/commit/eb0495324a85280748d2da2a3f3c16048534564c

This also should never clear enemy hunter guids, there's nothing especially wrong with that actually even for friendlies. All outdated guids get deleted after like an hour

**Comment by Dyaxler** [comment]
ooo... I like that even better. Much more elegant and it covers both in and out of raids and parties. I'll start testing this in my Dev build and provide some feedback soon.

**Comment by Dyaxler** [comment]
Just tested it with a fellow Guild hunter. I only tested Party and Raid since my addon doesn't track buff timers outside of that. The Feign Death didn't clear the timers and moving out of Combat Log range didn't reset it to Max Duration. Thank you!
