### ISSUE TITLE
Scorch refreshes Fire Vulnerability timer even when the debuff gets resisted

### ISSUE THREAD

**Issue by Hosq** [rgd87/LibClassicDurations#24]
Havent tested but i assume shadow vulnerability works the same way

**Comment by d87** [comment]
Nothing i can do about it

**Comment by d87** [comment]
Or maybe it's possible to rollback refresh if there's a resist event for debuff. But still it's not easily done without having an actual mage for testing

**Comment by Hosq** [comment]
https://puu.sh/EqZdP/1bcc54f061.png

**Comment by d87** [comment]
Is that at 5 stacks btw?

**Comment by Hosq** [comment]
had 4 stacks at that point

**Comment by d87** [comment]
Make sure resist event happens if on 5 pls

**Comment by Hosq** [comment]
https://puu.sh/EqZm9/67597aa672.png same event still even with 5 stacks

**Comment by d87** [comment]
Get the latest commit from github and check if its ignoring resists now

**Comment by Hosq** [comment]
yea ignores resists now but noticed that when you have 5 stacks it doesnt refresh timer on absorbs
https://puu.sh/Er2cM/e49c0cd4a3.png heres combatlog for that incase you need it
