### ISSUE TITLE
Diminishing Returns errors

### ISSUE THREAD

**Issue by bobjackson321** [rgd87/LibClassicDurations#25]
- Pounce and Cheap Shot are not "opener stuns". They DR with other normal stuns

- Kidney Shot only diminishes with itself.

- Scatter Shot diminishes with incap effects.

- Random Roots are not subjected to diminishing returns. (Only tested improved wing clip and entrapment) 

- Goblin Rocket helm is incap.

- Magic Dust is incap.

- Flash Bomb is probably fear.

**Comment by d87** [comment]
>Pounce and Cheap Shot are not "opener stuns". They DR with other normal stuns
>Kidney Shot only diminishes with itself.

You actually tested that?

**Comment by bobjackson321** [comment]
Yes. Cheap Shot/Kidney Shot was not swapped around until wrath.

> Patch 3.0.8 (2009-01-20): Cheap Shot no longer has diminishing returns against anything other than itself.

> Patch 3.0.8 (2009-01-20): Kidney Shot now has diminishing returns against all other stuns.

Scatter shot i tested on classic beta, but from what i have heard from hunters its still the same.

**Comment by d87** [comment]
Ok. thanks for finding that
