### ISSUE TITLE
Paladin Blessing timers reset upon re-entry of Combat Log range.

### ISSUE THREAD

**Issue by Dyaxler** [rgd87/LibClassicDurations#28]
If you cast a Blessing on a player then go out of Combat Log range, upon re-entry the timer is reset to max duration and begins counting down again.

I noticed in the code comments under Priest you have this...

> -- Long raid buffs now have cast filter, that is only if you directly casted a spell it'll register

And the Priest Buffs are marked with an additional castFilter value. I've marked all the Paladin blessings with **castFilter = true** values and the issue goes away. Can you update the classAbilities.lua with this?

**Comment by d87** [comment]
Done

**Comment by Dyaxler** [comment]
@d87 I have a new problem now. Setting **castFilter = true** does in fact solve the out of combat range resetting the buff timer to max duration.

However, now LibClassicDurations seems to only cache a "Class Buff" for the person it's cast on and skips assigning expiration values for all the other members of that class. The "others" have no timers. I'm at a loss as to why I'm loosing the other timers where I wasn't before. So maybe I'm not 100% understanding the **castFilter** scope.

Is it something that's missing from LibClassicDurations or do I require an extra loop and "fake" a cast on every player in the class to kick it into the **buffCache**?

**Comment by d87** [comment]
Damn, sorry. i tried to change how castfilter works recently to include long buffs from everyone, not just player and forgot about the raidwide buff case

**Comment by d87** [comment]
Alright i rolled back the castFilter change on curse repo for now
And here's the new castfilter version
https://github.com/rgd87/LibClassicDurations/commit/4bc7013827253e53d1ac01b2b5f37f5906a64504

**Comment by d87** [comment]
Should work now
