### ISSUE TITLE
Embedding needs to be fixed

### ISSUE THREAD

**Issue by mrbuds** [rgd87/LibClassicDurations#3]
Recommendations in the README for embedding lib are not acceptable, can you fix lib layout so .pkgmeta from other addons can link this github directly without making them use workarounds ?

**Comment by d87** [comment]
What are you talking about exactly? Having a CF repo link instead of github link?

**Comment by Stanzilla** [comment]
See the discussion on Discord, Buds mostly opened the issue because I suggested it, so my bad.
