### ISSUE TITLE
UnitAura from GUID

### ISSUE THREAD

**Issue by ccharly** [rgd87/LibClassicDurations#30]
Hi there, is there anyway I can get auras informations (using `UnitAura` wrapper) from a GUID itself? I'm trying to play around with nameplates and already have them stored in a table of mine and I do have the GUID of each of them. Now I'd like to have the auras attached to the nameplate/unit itself.

I've looked at the code there and I might be able to try something around this (and submit a PR if you want to).

I just wanna make sure you don't have something already for this purpose? I might have missed something as I'm quite new with WoW addons.

Thanks a lot for your work. :)

**Comment by d87** [comment]
There's ```LCD:GetAuraDurationByGUID(dstGUID, spellID, srcGUID, spellName)```

But with nameplates you should just use nameplate unitIDs (like "nameplate3"). I don't see any reason to use guids with nameplates

**Comment by ccharly** [comment]
OK thanks for the quick reply. I'll give it a shot using unitID then. :)
