### ISSUE TITLE
Pet Buffs do not show duration

### ISSUE THREAD

**Issue by MenOfWar** [rgd87/LibClassicDurations#31]
Pet buffs such as dash and frenzy do not have a duration in it. Debuffs work fine (see screenshot)

![image](https://user-images.githubusercontent.com/20087762/67634026-680e9300-f8b7-11e9-8806-13d22676100d.png)

This issue has been previously reported here: https://www.wowinterface.com/downloads/info25006-ClassicAuraDurations.html#comments

**Comment by d87** [comment]
The problem is probably with individual buffs. FA, Mend Pet wasn't in the database of spells, and Dash conflicts with Druid's Dash. I added First Aid, Mend Pet, Frenzy, mayble it'll help

**Comment by MenOfWar** [comment]
Great, could you please update https://www.wowinterface.com/downloads/info25006-ClassicAuraDurations.html#info ?
