### ISSUE TITLE
Shadow vulnerability from ISB doesn't show duration

### ISSUE THREAD

**Issue by Aixler** [rgd87/LibClassicDurations#37]
The warlock talent Improved Shadow Bolt puts a debuff on the target for 12 seconds following a crit. The effect can be seen in the combat log as Shadow Vulnerability. 

However, unlike my dots, the duration isn't shown.
![image](https://user-images.githubusercontent.com/8914693/69222413-babb3200-0b79-11ea-88a5-6fdd9b7e57fb.png)
Is it possible to add this duration to LCD?

Combat log:
09:35:04> Aixler begins casting Shadow Bolt.
09:35:04> Jhuuthun's melee swing hits Raging Owlbeast for 129 Physical.(Critical)
09:35:04> Raging Owlbeast's attack was dodged by Jhuuthun.
09:35:04> Aixler's Shadow Bolt hits Raging Owlbeast for 129 Shadow.(Critical)
09:35:05> Raging Owlbeast is afflicted by Aixler's Shadow Vulnerability.
09:35:05> Aixler casts Shadow Bolt at Raging Owlbeast.
09:35:05> Aixler's Shadow Vulnerability (3) subsides.
09:35:05> Aixler's Shadow Bolt hits Raging Owlbeast for 76 Shadow.

**Comment by d87** [comment]
Alright, added it back. I'm not sure why it's was disabled
