### ISSUE TITLE
No timer for Earthshaker stun

### ISSUE THREAD

**Issue by Francy333** [rgd87/LibClassicDurations#38]
Unfortunately this stun is showing up with no timer (3 sec stun). Its a proc from the epic weapon Earthshaker, dropped in Molten Core.

![67461170-05aa5e00-f63d-11e9-8180-5df49d4436d6](https://user-images.githubusercontent.com/56952748/69424550-35767f80-0d29-11ea-9e80-5b23cd05a378.jpg)

![earthshaker](https://user-images.githubusercontent.com/56952748/69424654-7a021b00-0d29-11ea-9609-0cfc48417dc4.jpg)

**Comment by d87** [comment]
Done
