### ISSUE TITLE
[Request] Make the "GetLastRankSpellID" public library function (not a local function) and 'spellNameToID' table a public library variable

### ISSUE THREAD

**Issue by millanzarreta** [rgd87/LibClassicDurations#41]
Hi!

The **GetLastRankSpellID(_spellName_)** function of the lib is a function that would be useful to call from an addon that implements this library, but unfortunally, this is a local function. Currently the function is this:

```
local function GetLastRankSpellID(spellName)
    local spellID = spellNameToID[spellName]
    if not spellID then
        spellID = NPCspellNameToID[spellName]
    end
    return spellID
end
```

This function can be added easy to a library function and mantain a local reference with a code like this:

```
lib.GetLastRankSpellID = function(spellName)
    local spellID = spellNameToID[spellName]
    if not spellID then
        spellID = NPCspellNameToID[spellName]
    end
    return spellID
end
local GetLastRankSpellID = lib.GetLastRankSpellID
```

The **spellNameToID** variable already has a reference on the library:

```
lib.spellNameToID = lib.spellNameToID or {}
local spellNameToID = lib.spellNameToID
```

But the **NPCspellNameToID** variable is only a local variable:

```
local NPCspellNameToID = {}
```

It can be converted easy to a library variable and mantain a local reference with a code like this:

```
lib.NPCspellNameToID = lib.NPCspellNameToID or {}
local NPCspellNameToID = lib.NPCspellNameToID
```

<hr>

Ok, really with one of the two solutions is enough, or convert _GetLastRankSpellID_ function to a non local variable attached to the lib, or do the same with the _spellNameToID_ variable; but I think that doing both causes no harm.

I know this is not the main use of the library, but while we are already using this library, this function (or the variable) can also be very useful for obtaining a spellId from a spellName (with some limitations I already know) in some occasions.

Regards!

**Comment by d87** [comment]
https://github.com/rgd87/LibClassicDurations/commit/442d544a8063c16818714c3cfa4e7a2b9c8a36ad
btw, keep in mind that only spells that apply auras are in the db
