### ISSUE TITLE
Tier 2: Increased Rejuvenation Duration not Reflected

### ISSUE THREAD

**Issue by Mushoz** [rgd87/LibClassicDurations#53]
This library always returns 12 seconds for the duration of rejuvenation and does not take into account the increased duration by the 8/8 Stormrage set bonus that brings it up to 15 seconds. Is this something that could be fixed?

**Comment by d87** [comment]
https://github.com/rgd87/LibClassicDurations/archive/settracker.zip
Update to this, see if it works

**Comment by Mushoz** [comment]
Works perfectly! Tried it both with and without the full set equiped. The duration correctly reflected the 15 and 12 second duration respectively. Thank you very much for this extremely quick fix :)
