### ISSUE TITLE
Issue with Shaman talent Elemental Mastery

### ISSUE THREAD

**Issue by keksecgg** [rgd87/LibClassicDurations#57]
Hello, I have been looking into a Weakaura around the Shaman talent Elemental Mastery however I believe that it is not shown in the library. The Spell id for this aura is 16166. Would it be possible to get this added?

Thank you

**Comment by d87** [comment]
Weakaura for enemies? Because if it's for yourself it should work regardless

**Comment by d87** [comment]
Anyway, added

**Comment by keksecgg** [comment]
Thank you, yes weakaura for target
