### ISSUE TITLE
Some what persistent buffCache?

### ISSUE THREAD

**Issue by Dyaxler** [rgd87/LibClassicDurations#58]
So this Lib is awesome btw... only issue I have is when a /reload or /relog occurs you loose your buff timers... any chance you could expand the capabilities of the buffCache to also save when the buff was applied (time stamp) then dump the buffCache to an SV with a *some number* timebomb so if a user reloads or relogs you could reconstitute the buffCache from the SV on any entries that was made less than an *some number* ago - else remove the entry?

**Comment by d87** [comment]
The big problem is that Saved Variables only can be registered for an addon, so you'd have to have standalone library addon installed for it to work.
Also vast majority of people don't relog that often and don't event know about /reload.

But still i did it in https://github.com/rgd87/LibClassicDurations/tree/SVHydrate branch
You can try it out. (You'll need a standalone package installed and the updated toc for it)

**Comment by Dyaxler** [comment]
I have this library embedded into my addon. I could register the necessary SV tables I'll need there. I guess I should have been more specific and asked to have the library "support" saving to an SV when embedded with an addon. :D

I'll check out that branch and take a look. Cheers mate!

**Comment by Dyaxler** [comment]
@d87 I never could get this to work fully embedded. But I didn't spend a whole lot of time on it. I was more focused on getting the comm system rewritten and working on other addons. I haven't had time to fully review what you wrote in that branch you made for me either. Can it be fully embedded or does it (the library) actually need to be run as a separate addon?

**Comment by d87** [comment]
It's fine, i tested on ptr and released it. Yes, it needs the standalone lib package https://github.com/rgd87/LibClassicDurations/releases

**Comment by Dyaxler** [comment]
Hmm... installed it. Works for my Pally Alt (Test account) but not my Main player account. :D I keep getting nil values in the SV.

**Comment by Dyaxler** [comment]
I got it... so if you have other addons enabled that uses the "embedded library"... such as Healbot and ClassicAuraDurations... once I disabled those two addons the SV tables started to populate with real values.
