### ISSUE TITLE
Ignite duration failing at max stacks

### ISSUE THREAD

**Issue by Olorun** [rgd87/LibClassicDurations#59]
Once Ignite goes up to full stacks (5 stacks), the debuff duration is not refreshed, similar to what happened with the Winter's Chill / Sunder etc. where debuff duration doesn't refresh properly.
Here's some video evidence, you can see it in both the ignite weakaura as well as the debuffs shown above the target frame.
https://clips.twitch.tv/EnjoyablePricklyEchidnaFrankerZ

**Comment by d87** [comment]
Well ignite doesn't have stacks, so it's not that. What happened there i think is caused by short combat log range and should fix itself after the next patch

**Comment by d87** [comment]
Try this https://github.com/rgd87/LibClassicDurations/releases/tag/1.57
