### ISSUE TITLE
Debuff no timer issue

### ISSUE THREAD

**Issue by wygsephi** [rgd87/LibClassicDurations#6]
Tukz guided me here to open a new issue on what I found. I am playing Warlock in Classic but the debuff Curse of Agony does not show a timer on the target's debuff, nor does it show on the target health bar. See the picture attached. Thanks!

![Screen Shot 2019-08-30 at 4 09 44 AM](https://user-images.githubusercontent.com/15519080/64008623-15457480-cadc-11e9-891d-c706003754b5.png)

**Comment by d87** [comment]
https://github.com/rgd87/ClassicAuraDurations/issues/5
I know about this and don't know what wrong with chinese client

**Comment by wygsephi** [comment]
Ohh did not know it happens only on chinese client. Hmm I guess it is okay when leveling. Thank you though!
