### ISSUE TITLE
Addons with non-embedded versions of LibClassicDurations - nil values in the SV tables

### ISSUE THREAD

**Issue by Dyaxler** [rgd87/LibClassicDurations#61]
I also use Healbot and ClassicAuraDurations... once I disabled those two addons I was able to keep all my buff timers after a relog/reloadUI

**Comment by d87** [comment]
Should be fixed now

**Comment by Dyaxler** [comment]
Manually updating Healbot and ClassicAuraDurations to the latest bits doesn't help either....

...oh ok. Trying your latest bits now. Just saw your response as I was typing.

**Comment by Dyaxler** [comment]
Confirmed... I reverted everything and both toons are working. :)

/cheers
