### ISSUE TITLE
Rake ability DoT effect

### ISSUE THREAD

**Issue by NotaBeneRnD** [rgd87/LibClassicDurations#69]
Wrong time for druid Rake ability DoT effect (12 sec instead 9 sec).
WoW Classic version.

**Comment by d87** [comment]
https://github.com/rgd87/LibClassicDurations/blob/36e4dff1eae6a3b70e56e6387268c7756091a45c/classAbilities.lua#L435
It's 9

**Comment by NotaBeneRnD** [comment]
Hi, yes, i see this string in lib, but ingame WA2 show 12sec debuff timer (pls look this, here screenshots):
https://github.com/WeakAuras/WeakAuras2/issues/2260

**Comment by d87** [comment]
Сделай
/dump LibStub("LibClassicDurations"):GetLastRankSpellIDByName("Глубокая рана")
/dump LibStub("LibClassicDurations"):GetLastRankSpellIDByName("Разорвать")
Что пишет?

Другой аддон с LCD попробуй, например ClassicAuraDurations. Там тоже 12?

**Comment by NotaBeneRnD** [comment]
Сделано!
![dump](https://user-images.githubusercontent.com/68054544/87709120-746fae80-c7ac-11ea-84e1-26e38d213d72.jpg)
Как я понял в этом корень зла:
https://ru.classic.wowhead.com/spell=12721/%D0%B3%D0%BB%D1%83%D0%B1%D0%BE%D0%BA%D0%B0%D1%8F-%D1%80%D0%B0%D0%BD%D0%B0
Глубокая рана - Длительность 12 сек.
А как это исправить?

**Comment by d87** [comment]
https://github.com/rgd87/LibClassicDurations/releases/download/1.62.1/LibClassicDurations-1.62.1-classic.zip
Установи это

**Comment by NotaBeneRnD** [comment]
Спасибо, доктор! Теперь все как надо.
