### ISSUE TITLE
Intermittent timer issues... 

### ISSUE THREAD

**Issue by Dyaxler** [rgd87/LibClassicDurations#70]
So I've been debugging this for a week or so. It's fairly rare for it to occur so sadly I don't have a repro for you. Sometimes when buffing a unit the duration will return with a zero. Happens on single units and with groups of units (group buffs). With group buffs some units will return zero's but usually only one or two. The rest are usually ok.

During my own sessions if I encounter a 0:00 unit I've tried manually updating that button which will go through the same LCD calls. Still returns with 0:00. If I reload my UI it still returns with a 0:00. The only way to fix it is to rebuff the unit.

My only assumption from this behavior and from details gathered by other users is that the LDC tables that store when a buff is cast... doesn't get done or there is some race condition that is preventing it from happening. Maybe a players GUID isn't returned in time to calc the duration remaining value so it returns zero?

**Comment by d87** [comment]
Idk, things just aren't perfect. Mass buffs especially depend on a particular weird event order. Combat log range up to 1.13.5 was short and is still short outdoors.

**Comment by Dyaxler** [comment]
Hmmm... bummer. I was hoping you might have an idea. I've been running with debug enabled and I see the SPELL_AURA_APPLIED and SPELL_CAST_SUCCESS events along with the GUID's... but for some reason the LCD_Data table doesn't contain the casted buff listed. So even if I reload my UI the buff comes up 0:00. It's like the events are captured but the cast time isn't captured/saved.

**Comment by Dyaxler** [comment]
I could write up my own "fail safe" - if buff returns a duration of 0:00 then GetTime() and then push it to the LCD_Data table. At worse the timers would be 1 second off since it's called every second. But I'd rather not reinvent the wheel if were already planning on doing something like that. :)

**Comment by d87** [comment]
0 duration means no data, the game returns 0 too. LCD_Data is only used on logout.

Try increasing this to more than 0.4. 
https://github.com/rgd87/LibClassicDurations/blob/206120722bb13a457240027335675de748d0cb5d/core.lua#L634

And separately try removing castFilter altogether from the buffs you're casting
https://github.com/rgd87/LibClassicDurations/blob/206120722bb13a457240027335675de748d0cb5d/classAbilities.lua#L258

I don't remember why it's still enabled at all. In theory it's pointless now.

**Comment by Dyaxler** [comment]
If I remove all the "castFilter" entries then increasing the timer is pointless...  ;)

`            if opts.castFilter then
                -- Buff and Raidwide Buff events arrive in the following order:
                -- 1571716930.161 ID: 21562 SPELL_AURA_APPLIED/REFRESH to Caster himself (if selfcast or raidwide)
                -- 1571716930.161 ID: 21562 SPELL_CAST_SUCCESS on Cast Target
                -- 1571716930.161 ID: 21562 SPELL_AURA_APPLIED/REFRESH to everyone else

                -- For spells that have cast filter enabled:
                    -- First APPLIED event gets snapshotted and otherwise ignored
                    -- CAST event effectively sets castEventPass to true
                    -- Snapshotted event now gets handled with cast pass
                    -- All the following APPLIED events are accepted while cast pass is valid
                    -- (Unconfirmed whether timestamp is the same even for a 40m raid)
                local now = GetTime()
                castEventPass = castLog:IsCurrent(srcGUID, spellID, now, 0.8)
                if not castEventPass and (eventType == "SPELL_AURA_REFRESH" or eventType == "SPELL_AURA_APPLIED") then
                    eventSnapshot = { timestamp, eventType, hideCaster,
                    srcGUID, srcName, srcFlags, srcFlags2,
                    dstGUID, dstName, dstFlags, dstFlags2,
                    spellID, spellName, spellSchool, auraType }
                    return
                end

                if eventType == "SPELL_CAST_SUCCESS" then
                    -- Aura spell ID can be different from cast spell id
                    -- But all buffs are usually simple spells and it's the same for them
                    castLog:SetLastCast(srcGUID, spellID, now)
                    if eventSnapshot then
                        self:CombatLogHandler(unpack(eventSnapshot))
                        eventSnapshot = nil
                    end
                end
            end`

**Comment by d87** [comment]
I know, try both

**Comment by Dyaxler** [comment]
Yeah, I thought that's what you meant. :)

Man, you know it seems to me like there are more and more "race conditions" popping up since the last patch. I've been having some weird issues with PallyPower and other addons in general.

**Comment by d87** [comment]
btw originally castFilter was used to distinguish between actual APPLIED events after a spellcast and APPLIED events that were generated for every aura when someone came inside combat log range. But then they removed these auto events with Spy patch.
I still left cast filter on because it was seemingly working and i was afraid that removing it would cause some random issues. (And as i don't even play i'd have no idea)

**Comment by Dyaxler** [comment]
I remember when you added the filters to Pally buffs but I don't recall the reason. Getting old sucks... sigh.

So increasing the time didn't work. Got a 0:00 on a pet... removing the castFilters from Pally buffs and I'll give that a few trys.

**Comment by Dyaxler** [comment]
OK, I vaguely remember why you added castFilters to Pally Buffs... if you buffed someone and moved out of range the timers would just simply stop and moving back into range would resume them? Maybe that was it?

Doesn't matter I guess. Removing the castFilters so far hasn't broken anything. Moving in and out of range I can see the SPELL_AURA_REMOVED and SPELL_AURA_APPLIED events firing. The timers are unaffected and still count down normally. They don't stop or clear which is good.

**Comment by Dyaxler** [comment]
Hmmm... this is new. SPELL_CAST_FAILED is appearing. But that is due to spamming the buff and GCD is active. I don't recall seeing that event fire before. But no 0:00 yet... I'll keep trying it out.

**Comment by d87** [comment]
Well they shouldn't be. Are you inside the instance? And it's weird that it is still working. Did you bump the version at the top of classAbilities.lua to make sure it's the one that gets used?

**Comment by Dyaxler** [comment]
Doh! That might be why I still got a 0:00 :D I keep forgetting that Healbot and ClassicAuraDurations uses this lib.

**Comment by Dyaxler** [comment]
And BTW... the 0:00 buff timer thing isn't limited to range or location. It happens (< 100 yards and > 40 yards) and < 40 yards and in or outside of an instance.

**Comment by Dyaxler** [comment]
Went back to the 0.8 timer mod and keeping the castFilters... in a BG and so far NO 0:00

**Comment by Dyaxler** [comment]
I left instructions on how to modify LCD in my Discord. I should get a few testers to try it out... I'll let you know what we find out.

**Comment by Dyaxler** [comment]
I got back two more independent confirmations that increasing the castEventPass threshold from 0.4 to 0.8 seems to have done the trick. No 0:00's encountered.

**Comment by d87** [comment]
Alright, I released an update

**Comment by Dyaxler** [comment]
Thank you so much man!

/cheers

**Comment by cont1nuity** [comment]
I can check if I missed anything, but I'd say it is best to open an issue with LibClassicDurations.
I can push an update to Plater as soon as I have confirmation that this is fixed.
