### ISSUE TITLE
classAbilities.lua  added

### ISSUE THREAD

**Issue by murer9788** [rgd87/LibClassicDurations#77]
i added this code.

Spell({ 349981, 349981 }, { duration = INFINITY }) -- World effect suspended
Spell( 28142, { duration = INFINITY, type = "BUFF" }) -- Power of the Guardian
Spell( 28143, { duration = INFINITY, type = "BUFF" }) -- Power of the Guardian
Spell( 28144, { duration = INFINITY, type = "BUFF" }) -- Power of the Guardian
Spell( 28145, { duration = INFINITY, type = "BUFF" }) -- Power of the Guardian

now i can see enemy player  "Power of the Guardian buff" and "Supercharged Chronoboon Displacer" buff

**Comment by d87** [comment]
Thanks, added them
